#!/usr/bin/env python3
"""
publication_index.py — the only writer of PUBLICATION_INDEX.md.

    --build     render PUBLICATION_INDEX.md from publication/trisduction_ledger.json
    --verify    reconcile the ledger against live Zenodo, live Internet Archive, and git
    --add KEY   scaffold a new ledger entry from flags

The ledger is the source. The index is derived and must never be hand-edited: an edit there
is lost on the next build and, worse, is invisible until it is. This mirrors tools/build_index.py
for the codex and publication/label_map.py for the label map, which are likewise sole writers.

Build is deterministic. It renders twice and asserts the two runs agree byte for byte before
it writes anything, the same guard label_map.py applies.
"""
import argparse, collections, hashlib, json, os, re, subprocess, sys, time, urllib.error, urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(REPO, 'publication', 'trisduction_ledger.json')
INDEX = os.path.join(REPO, 'PUBLICATION_INDEX.md')
SCHEMA = 'trisduction-unified-permanence-ledger/2'
THROTTLE = 0.7   # seconds between anonymous API calls

DOMAIN_ORDER = ['Verification Architecture', 'Root Axiom and Ontology', 'Riemann Hypothesis',
                'P versus NP and Foundations', 'Physics', 'AI and Machine Ethics',
                'Scripture and Theology', 'Unfiled']

CORE = {'title', 'subtitle', 'domain', 'status', 'first_published', 'last_updated', 'git',
        'zenodo', 'ia', 'philarchive', 'supersedes', 'superseded_by', 'note', 'extra'}


# ----------------------------------------------------------------- helpers
def load():
    with open(LEDGER, encoding='utf-8') as fh:
        d = json.load(fh)
    if d.get('schema') != SCHEMA:
        sys.exit(f'ledger schema is {d.get("schema")!r}, expected {SCHEMA!r}')
    return d


def save(d):
    with open(LEDGER, 'w', encoding='utf-8') as fh:
        json.dump(d, fh, indent=1, ensure_ascii=False)
        fh.write('\n')


def sortkey(item):
    k, w = item
    return (w.get('last_updated') or '', w.get('first_published') or '', k)


def git_tracked():
    out = subprocess.run(['git', '-c', 'core.quotepath=false', 'ls-files'],
                         cwd=REPO, capture_output=True, text=True)
    return set(out.stdout.splitlines())


def get_json(url, timeout=45, tries=4):
    """Throttled fetch. Zenodo and IA rate-limit anonymous callers; a 429 is backed off
    and retried rather than reported as a dead address, which would be a false failure."""
    last = None
    for n in range(tries):
        try:
            req = urllib.request.Request(url, headers={'Accept': 'application/json',
                                                       'User-Agent': 'trisduction-index'})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                out = json.loads(r.read())
            time.sleep(THROTTLE)
            return out
        except urllib.error.HTTPError as e:
            last = e
            if e.code in (429, 500, 502, 503, 504):
                time.sleep(2 ** n * 1.5)
                continue
            raise
    raise last


def cell(v):
    return v if v else '—'


def link(text, url):
    return f'[{text}]({url})' if url else '—'


# ------------------------------------------------------------------- build
def render(d):
    works = d['works']
    n = len(works)
    zen = [w for w in works.values() if (w.get('zenodo') or {}).get('concept_doi')]
    ia = [w for w in works.values() if (w.get('ia') or {}).get('identifier')]
    gitp = [w for w in works.values() if (w.get('git') or {}).get('pdf')]
    pa = [w for w in works.values() if (w.get('philarchive') or {}).get('record')]
    status = collections.Counter(w.get('status', 'unknown') for w in works.values())
    versions = sum((w.get('zenodo') or {}).get('versions') or 0 for w in works.values())

    L = []
    L.append('# PUBLICATION INDEX')
    L.append('')
    L.append('Generated by `tools/publication_index.py` from `publication/trisduction_ledger.json`.')
    L.append('**Auto-generated. Do not hand-edit.** To change a row, edit the ledger and rebuild:')
    L.append('')
    L.append('    python3 tools/publication_index.py --build')
    L.append('')
    L.append('The ledger is the source of record for surface addresses. The live surfaces are the '
             'source of record for surface *state*; run `--verify` to reconcile the two. A pointer '
             'file is advisory and never overrides what is actually present.')
    L.append('')

    # ---- at a glance
    L.append('## Corpus at a glance')
    L.append('')
    L.append(f'**{n} works · {versions} Zenodo deposits.**')
    L.append('')
    L.append('| Surface | Works carrying an address | Coverage |')
    L.append('|---|---|---|')
    for label, sub in (('Zenodo', zen), ('Git PDF', gitp),
                       ('Internet Archive', ia), ('PhilArchive', pa)):
        L.append(f'| {label} | {len(sub)} / {n} | {100*len(sub)//n if n else 0}% |')
    L.append('')
    L.append('Status: ' + ', '.join(f'{v} {k}' for k, v in sorted(status.items())) + '.')
    L.append('')

    # ---- gaps: the section that earns the file
    L.append('## Coverage gaps')
    L.append('')
    L.append('The only view in the repository that answers "what is published where, and what '
             'is missing." Each list is a work queue, not an error.')
    L.append('')
    no_ia = sorted([(k, w) for k, w in works.items()
                    if not (w.get('ia') or {}).get('identifier')], key=sortkey)
    no_git = sorted([(k, w) for k, w in works.items()
                     if not (w.get('git') or {}).get('pdf')], key=sortkey)
    no_zen = sorted([(k, w) for k, w in works.items()
                     if not (w.get('zenodo') or {}).get('concept_doi')], key=sortkey)
    amb = sorted([(k, w) for k, w in works.items()
                  if (w.get('extra') or {}).get('git_match_ambiguous')], key=sortkey)

    def gap(title, items, note):
        L.append(f'### {title} ({len(items)})')
        L.append('')
        if not items:
            L.append('None.')
        else:
            L.append(note)
            L.append('')
            for k, w in items:
                L.append(f'- `{k}` · {w["title"][:110]}')
        L.append('')

    gap('On Zenodo, not on the Internet Archive', no_ia,
        'Deposited to Zenodo but no IA item located. IA is the second permanence surface; '
        'a work here has one address, not two.')
    gap('No PDF matched in this repository', no_git,
        'A Zenodo deposit with no corresponding PDF found under `Publication Library/`. Either '
        'the file was never filed in git, or it is filed under a name the matcher could not tie '
        'to the title. Assign the path by hand in the ledger to close the row.')
    gap('In git or on IA, never deposited to Zenodo', no_zen,
        'No Zenodo concept, so no DOI and no citable permanent address.')
    gap('Git path withheld, ambiguous match', amb,
        'More than one work matched the same file, so no path is asserted. Resolve by hand.')

    # ---- master table
    L.append('## Index')
    L.append('')
    L.append('Work key leads each row; it is the stable identity and the grep target. '
             'The Zenodo column carries the **concept** DOI, which always resolves to the '
             'latest version.')
    L.append('')
    L.append('| Work key | Title | Domain | Status | Git | Zenodo concept | v | IA | PhilArchive | Updated |')
    L.append('|---|---|---|---|---|---|---|---|---|---|')
    for k, w in sorted(works.items(), key=sortkey, reverse=True):
        z = w.get('zenodo') or {}
        i = w.get('ia') or {}
        g = w.get('git') or {}
        p = w.get('philarchive') or {}
        zc = f'`{z["concept_doi"]}`' if z.get('concept_doi') else '—'
        gp = link('pdf', g['pdf'].replace(' ', '%20')) if g.get('pdf') else '—'
        pr = p.get('record')
        pa_cell = link('philarchive', pr) if pr and str(pr).startswith('http') else cell(pr)
        cells = [f'`{k}`', w['title'][:95].replace('|', '/'), w.get('domain', 'Unfiled'),
                 w.get('status', '?'), gp, zc, str(z.get('versions') or '—'),
                 link('ia', i.get('url')), pa_cell, cell(w.get('last_updated'))]
        L.append('| ' + ' | '.join(cells) + ' |')
    L.append('')

    # ---- by domain
    L.append('## By domain')
    L.append('')
    bydom = collections.defaultdict(list)
    for k, w in works.items():
        bydom[w.get('domain', 'Unfiled')].append((k, w))
    for dom in DOMAIN_ORDER:
        if dom not in bydom:
            continue
        items = sorted(bydom[dom], key=sortkey, reverse=True)
        L.append(f'### {dom} ({len(items)})')
        L.append('')
        L.append('| Work key | Title | Zenodo concept | v | IA | Updated |')
        L.append('|---|---|---|---|---|---|')
        for k, w in items:
            z = w.get('zenodo') or {}
            i = w.get('ia') or {}
            zc = f'`{z["concept_doi"]}`' if z.get('concept_doi') else '—'
            L.append(f'| `{k}` | {w["title"][:85].replace("|", "/")} | {zc} | '
                     f'{z.get("versions") or "—"} | {link("ia", i.get("url"))} | '
                     f'{cell(w.get("last_updated"))} |')
        L.append('')

    # ---- version chains
    multi = sorted([(k, w) for k, w in works.items()
                    if ((w.get('zenodo') or {}).get('versions') or 0) > 1], key=sortkey, reverse=True)
    L.append(f'## Zenodo version chains ({len(multi)})')
    L.append('')
    L.append('Works carrying more than one deposit. Full per-version DOIs and checksums are in '
             '`Zenodo Snapshot [2026-09-01]/MANIFEST.md`.')
    L.append('')
    L.append('| Work key | Versions | Concept DOI | Latest version DOI | First | Latest |')
    L.append('|---|---|---|---|---|---|')
    for k, w in multi:
        z = w['zenodo']
        L.append(f'| `{k}` | {z["versions"]} | `{z["concept_doi"]}` | '
                 f'`{z.get("latest_version_doi") or "—"}` | {cell(w.get("first_published"))} | '
                 f'{cell(w.get("last_updated"))} |')
    L.append('')

    L.append('## Maintaining this file')
    L.append('')
    L.append('On any new deposit to Zenodo or the Internet Archive:')
    L.append('')
    L.append('    python3 tools/publication_index.py --add <key> --title "..." \\')
    L.append('        --domain "..." --zenodo <conceptrecid> --ia <identifier> --git <path>')
    L.append('    python3 tools/publication_index.py --build')
    L.append('    git add publication/trisduction_ledger.json PUBLICATION_INDEX.md && git commit')
    L.append('')
    L.append('`--verify` reconciles every address against live Zenodo, live Internet Archive, and '
             '`git ls-files`, and reports four drift classes: an address the ledger claims that is '
             'not live, a live address the ledger does not carry, a git PDF with no ledger entry, '
             'and a version DOI superseded upstream. Skipping the ledger edit does not corrupt '
             'anything; `--verify` names the omission on the next run.')
    L.append('')
    return '\n'.join(L) + '\n'


def build():
    d = load()
    a, b = render(d), render(d)
    if a != b:
        sys.exit('build is not deterministic; refusing to write')
    prev = open(INDEX, encoding='utf-8').read() if os.path.exists(INDEX) else None
    with open(INDEX, 'w', encoding='utf-8') as fh:
        fh.write(a)
    print(f'wrote {os.path.relpath(INDEX, REPO)}  '
          f'{len(d["works"])} works  {len(a.splitlines())} lines  '
          f'sha256 {hashlib.sha256(a.encode()).hexdigest()[:16]}'
          f'{"  (unchanged)" if prev == a else ""}')


# ------------------------------------------------------------------ verify
def verify(offline=False):
    d = load()
    works = d['works']
    tracked = git_tracked()
    drift = collections.defaultdict(list)

    for k, w in sorted(works.items()):
        for field in ('md', 'pdf'):
            p = (w.get('git') or {}).get(field)
            if p and p not in tracked:
                drift['dead-git-path'].append(f'{k}: git.{field} → {p}')
        for f in w:
            if f not in CORE:
                drift['schema-drift'].append(f'{k}: unknown top-level field {f!r} (move into extra)')
        if not w.get('title'):
            drift['schema-drift'].append(f'{k}: missing required field title')
        if not any(((w.get(s) or {}).get(idf)) for s, idf in
                   (('git', 'pdf'), ('zenodo', 'concept_doi'), ('ia', 'identifier'))):
            drift['no-surface'].append(k)

    if not offline:
        for k, w in sorted(works.items()):
            z = w.get('zenodo') or {}
            if z.get('conceptrecid'):
                try:
                    latest = get_json('https://zenodo.org/api/records/'
                                      f'{z["conceptrecid"]}')
                    ndoi = latest.get('doi')
                    if not ndoi:
                        drift['dead-zenodo'].append(
                            f'{k}: concept {z["conceptrecid"]} returned no DOI')
                    elif z.get('latest_version_doi') and ndoi != z['latest_version_doi']:
                        drift['superseded'].append(
                            f'{k}: ledger latest {z["latest_version_doi"]}, '
                            f'Zenodo latest {ndoi} — new version deposited, ledger not updated')
                except urllib.error.HTTPError as e:
                    drift['dead-zenodo'].append(f'{k}: concept {z["conceptrecid"]} HTTP {e.code}')
                except Exception as e:
                    drift['unreachable'].append(f'{k}: zenodo {type(e).__name__}')
            i = w.get('ia') or {}
            if i.get('identifier'):
                try:
                    m = get_json(f'https://archive.org/metadata/{i["identifier"]}')
                    if not m.get('metadata'):
                        drift['dead-ia'].append(f'{k}: IA {i["identifier"]} is empty or missing')
                except Exception:
                    drift['unreachable'].append(f'{k}: ia unreachable')

    claimed = {(w.get('git') or {}).get('pdf') for w in works.values()}
    for p in sorted(tracked):
        if (p.lower().endswith('.pdf') and p.startswith('Publication Library/')
                and p not in claimed):
            drift['unledgered-pdf'].append(p)

    hard = ('dead-git-path', 'dead-zenodo', 'dead-ia', 'schema-drift', 'no-surface')
    print(f'VERIFY · {len(works)} works · '
          f'{"offline" if offline else "live surfaces checked"}')
    print()
    if not drift:
        print('  clean, no drift')
    for cls in sorted(drift):
        mark = 'FAIL' if cls in hard else 'note'
        print(f'  [{mark}] {cls} ({len(drift[cls])})')
        for row in drift[cls][:40]:
            print(f'         {row}')
        if len(drift[cls]) > 40:
            print(f'         … and {len(drift[cls]) - 40} more')
    summary = os.environ.get('GITHUB_STEP_SUMMARY')
    if summary:
        with open(summary, 'a', encoding='utf-8') as fh:
            fh.write(f'### Publication index verify\n\n{len(works)} works.\n\n')
            for cls in sorted(drift):
                fh.write(f'- **{cls}**: {len(drift[cls])}\n')
    return 1 if any(c in drift for c in hard) else 0


# --------------------------------------------------------------------- add
def add(args):
    d = load()
    if args.add in d['works'] and not args.force:
        sys.exit(f'work key {args.add!r} already present; pass --force to overwrite')
    cid = args.zenodo
    entry = {
        'title': args.title or '',
        'domain': args.domain or 'Unfiled',
        'status': args.status,
        'first_published': args.date,
        'last_updated': args.date,
        'git': {'md': args.git_md, 'pdf': args.git, 'editions': []},
        'zenodo': ({'conceptrecid': int(cid), 'concept_doi': f'10.5281/zenodo.{cid}',
                    'latest_version_doi': args.zenodo_version, 'latest_record': None,
                    'versions': args.versions, 'state': 'published'} if cid else
                   {'conceptrecid': None, 'concept_doi': None, 'latest_version_doi': None,
                    'latest_record': None, 'versions': 0, 'state': 'not-deposited'}),
        'ia': ({'identifier': args.ia, 'url': f'https://archive.org/details/{args.ia}',
                'state': 'live'} if args.ia else
               {'identifier': None, 'url': None, 'state': 'not-deposited'}),
        'philarchive': {'record': args.philarchive, 'url': None},
        'supersedes': args.supersedes, 'superseded_by': None,
        'note': args.note, 'extra': {},
    }
    d['works'][args.add] = entry
    save(d)
    print(f'added {args.add!r}. Now run --build, then commit both files.')


# -------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--build', action='store_true')
    ap.add_argument('--verify', action='store_true')
    ap.add_argument('--offline', action='store_true', help='verify without network calls')
    ap.add_argument('--add', metavar='KEY')
    ap.add_argument('--title'); ap.add_argument('--domain'); ap.add_argument('--git')
    ap.add_argument('--git-md'); ap.add_argument('--zenodo'); ap.add_argument('--zenodo-version')
    ap.add_argument('--ia'); ap.add_argument('--philarchive'); ap.add_argument('--note')
    ap.add_argument('--supersedes'); ap.add_argument('--date', default='')
    ap.add_argument('--status', default='live'); ap.add_argument('--versions', type=int, default=1)
    ap.add_argument('--force', action='store_true')
    a = ap.parse_args()
    if a.add:
        add(a)
    elif a.verify:
        sys.exit(verify(offline=a.offline))
    elif a.build:
        build()
    else:
        ap.print_help()


if __name__ == '__main__':
    main()
